version: '3.8'

services:
  db:
    image: postgres:15-alphine
    container_name: herera_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: herera_secure_pwd
      POSTGRES_DB: herera_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: herera_backend_container
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
